spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: ${DB_USERNAME:woderbar}
    password: ${DB_PASSWORD:woderbar1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

