package com.woderbar.domain.type;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorType {

    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED_ERROR,
    FORBIDDEN_ERROR,
    BAD_REQUEST_ERROR,

    NO_APP_VERSION_PRESENT_ERROR,
    INCOMPATIBLE_APP_VERSION_ERROR,
    FILE_CONTAINER_TYPE_ERROR,
    CLUB_NOT_FOUND_ERROR,
    SEASON_NOT_FOUND_ERROR,
    ACTIVE_SEASON_NOT_FOUND_ERROR,
    START_DATE_ERROR,
    END_DATE_ERROR,
    DATE_TAKEN_ERROR,
    CURRENCY_NOT_FOUND_ERROR,
    SPORT_NOT_FOUND_ERROR,
    TEAM_NOT_FOUND_ERROR,
    TEAM_BAD_REQUEST_ERROR,
    TEAM_NAME_ERROR,
    TEAM_ASSIGMENT_BAD_REQUEST_ERROR,
    ATHLETE_NOT_FOUND_ERROR,
    ATHLETE_BAD_REQUEST_ERROR,
    EMAIL_TAKEN_ERROR,
    PAYMENT_PRODUCT_NOT_FOUND_ERROR;

    public static final String FILE_CONTAINER_TYPE_ERROR_KEY = "FILE_CONTAINER_TYPE_ERROR";
    public static final String TEAM_ASSIGMENT_BAD_REQUEST_ERROR_KEY = "TEAM_ASSIGMENT_BAD_REQUEST_ERROR";
    public static final String TEAM_NAME_ERROR_KEY = "TEAM_NAME_ERROR";
}
